# Travis CI

language: ruby
cache: bundler
sudo: false
rvm: 2.1
env:
  global:
    - BUNTO_VERSION=3.0.0
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - bundle update
script: script/cibuild
notifications:
  email:
    on_success: never
    on_failure: never
